name: push-CI

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  lint-n-test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]


    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - run: pip install -r requirements-dev.txt

    - name: Checking with isort
      run: |
        isort -c src

    - name: Checking with black
      run: |
        black --check --color --line-length 120 src

    - name: Linting with pylint
      run: |
        pylint src
